name: Java

on:
  push:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
      
      # - name: Test & publish code coverage
      #   uses: paambaati/codeclimate-action@v2.5.7
      #   env:
      #    cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     coverageCommand: mvn test
      #     debug: true
      - name: Generate Coverage Report
        # run: mvn clean verify
        run: ls -la ./target
      - name: Archive Jacoco reports
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-reports
          path: target/site/jacoco/*